language: php

php:
  - 7.0

sudo: false

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

install:
  - composer install

script:
  - ./vendor/bin/typo3cms install:setup --database-socket="" --site-name="Site"  --non-interactive
