language: php

php:
  - 7.0

sudo: false

matrix:
  fast_finish: true

cache:
  apt: true

before_install:
  - echo $TRAVIS_PHP_VERSION
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

install:
  - composer install

script:
  - ./vendor/bin/typo3cms install:setup --database-socket="" --site-name="Site"  --non-interactive
